name: Test Doc build

on:
   pull_request:
   push:
     branches:
       - main
   workflow_dispatch:

jobs:
  doc-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update the system
        run: |
          sudo apt update -y

      - name: Install dependencies
        run: |
          sudo apt install -y python3 python3-docutils python3-sphinx

      - name: Check documentation
        run: |
          make html

      - name: Deploy to temporary link
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}
          publish_dir: ./output/html
